name: e_commerce_graduation
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  flutter_xlider: ^3.5.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.3.0
  iconsax: ^0.0.8
  intl: ^0.19.0
  line_icons: ^2.0.3
  restart_app: ^1.3.2
  shared_preferences: ^2.4.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.11.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/auth/
    - assets/images/other/
    - assets/images/home_page/
  fonts:
    - family: rubic
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-ExtraBold.ttf
        - asset: assets/fonts/Rubik-ExtraBoldItalic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik-SemiBoldItalic.ttf
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraBold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
flutter_intl:
  enabled: true
