// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzsE1VgM2iTcjZ9Q7i6gO_-Czz4KuYEF4',
    appId: '1:1016122638985:web:6c3653163b22f7b301fc58',
    messagingSenderId: '1016122638985',
    projectId: 'e-commerce-auth-c4f8d',
    authDomain: 'e-commerce-auth-c4f8d.firebaseapp.com',
    storageBucket: 'e-commerce-auth-c4f8d.firebasestorage.app',
    measurementId: 'G-GLFCYF7Z3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiFZXiK04vsYSL-j2_mtL378ZCL4u7pUk',
    appId: '1:1016122638985:android:dac044c02dc9d76501fc58',
    messagingSenderId: '1016122638985',
    projectId: 'e-commerce-auth-c4f8d',
    storageBucket: 'e-commerce-auth-c4f8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB90eKnlQBZ7N1ztdMSwkaFwZy8H2_fSWY',
    appId: '1:1016122638985:ios:b2f5d736b7b3117c01fc58',
    messagingSenderId: '1016122638985',
    projectId: 'e-commerce-auth-c4f8d',
    storageBucket: 'e-commerce-auth-c4f8d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceGraduation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB90eKnlQBZ7N1ztdMSwkaFwZy8H2_fSWY',
    appId: '1:1016122638985:ios:b2f5d736b7b3117c01fc58',
    messagingSenderId: '1016122638985',
    projectId: 'e-commerce-auth-c4f8d',
    storageBucket: 'e-commerce-auth-c4f8d.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceGraduation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzsE1VgM2iTcjZ9Q7i6gO_-Czz4KuYEF4',
    appId: '1:1016122638985:web:23df7f8f12059e1401fc58',
    messagingSenderId: '1016122638985',
    projectId: 'e-commerce-auth-c4f8d',
    authDomain: 'e-commerce-auth-c4f8d.firebaseapp.com',
    storageBucket: 'e-commerce-auth-c4f8d.firebasestorage.app',
    measurementId: 'G-GPKQTVGBBZ',
  );
}
