import 'package:flutter/material.dart';

class CategoryTap extends StatelessWidget {
  const CategoryTap({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
            child: SingleChildScrollView(
      child: Column(
        children: [
          Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
          // Text('Category Tap'),
        ],
      ),
    )));
  }
}
